dist: trusty
sudo: require
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libgles2-mesa
    - libegl1-mesa
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install:
- wget -O qt.run http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
- wget -O qt-non-interactive.qs https://gist.github.com/waicool20/f5d00e90e3186fb09404f609ea5f078d/raw/
- chmod +x qt.run
- "./qt.run --script ./qt-non-interactive.qs --platform minimal --verbose"
- wget https://cmake.org/files/v3.9/cmake-3.9.2-Linux-x86_64.sh
- sudo sh cmake-3.9.2-Linux-x86_64.sh -- --skip-license --prefix=/usr
before_script:
- export CC=/usr/bin/gcc-7
- export CXX=/usr/bin/g++-7
- export CMAKE_PREFIX_PATH=~/Qt/5.9.1/gcc_64/
- export PATH=$PATH:~/Qt/5.9.1/gcc_64/bin/
script:
- cd $TRAVIS_BUILD_DIR
- "./gradlew build"
- "./gradlew dokka"
deploy:
- provider: script
  skip_cleanup: true
  script: "./gradlew publish"
  on:
    branch: master
- provider: pages
  local_dir: "$TRAVIS_BUILD_DIR/build/javadoc/"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
env:
  global:
  - secure: oxrBKU7V1rPOeu8hZAKmj0t4ji1gu/VdoA6c5UWejHqprApsexhLiXdSEtlNXkQixZh67y2JQaZyhIogA7CasH4Ok3hpExKV70j6Wq7hvOi/4Cbxval0QFwXBDs56WcmFrKZGFbYeLBHMEvz5ReT/oB2Ck34nHISqDBgxS6Oj+K4UMyd+kFpu0I/K8IOAcWPpX8lxxnWl9vIqIqLKQNE1wDOK5OAkI3ONO+xHVcbFDqraWyrPG4PP5tba0q+05ykCHBoMRoK3tK2xE6ylUy1qRDbQdWTPwlj4cXEagwuotruTP6+7sRJXS966YVZj5msI0Xx+AWOh2p4nMEVQjxixrqJndYTeaDHdtB06maQrszyvKpSSAi8GeybrU7LPgaEXLRX6bUWqiLci9a3YX42xTEw9EfxEfJIF6Fmjxws+XT4ZozgiDpdUAPawfL7u0UX3GJMKqjM60a1EqGsfTKfeZyuZA4plXFuMeCDUQ0g3KlpIIt+2AR26zby87RyJkeAWUUHfTp7xaxQKXqqlCWguYvlhh+VKau7GtpZpR1gzN/xktkdz2fGjG+aiTSddhQvPrEtHwr8YwdK2ejv9O6bHHDV/FZ2ExrTR2uHdtP0eL4eZeV/mIu1+/j2QdcGRXbmYr4x96cKsQK/JwFFR2SarYBKUoUBfpa/ILW1sJ+qEb0=
  - secure: IVvhjCxPs5lchDRi8wpFnYm5ad9UraLhQGSCVdw8+9SERm964qi9Ip7fjGC85G0MzFU/Za9y+Datvw6b6ycRrlHoPXP1SQwHVIEkKMJjEWIfabMW2sTHFph8VdZqx6FvsvizvVQY04FANk4ALKCEQmBCWy05mFzMVPnppgbK4vtvdCEBhXDFsAdBhjfhrCVKq2atG4/AKGor0iNvDjrQly+xFUgyxN2UuAGFkCPMvnAMCWR5Aln4xID3ohi5TRomSpvBBkMvXVn6qj+iZRwzAXGBG691kHQwND1Fly7ZnOeOMWGVCyDC1R9/ed4QAx1E2c6VFDSRcUI/83vc34dRPImdELAEQruTNPN/gwV4AZZQiGqcJ+UU2gIa9erYZeonHQJfPZS2BpjhQEUqKxfEm0jvEk/fYxMHZ1VOurINzdDppgX5qy628XzRwrAL1QPmmtchzL8Jg/J4HoYIsTSESphVXAuQF2mgrzk7KWez0rZXZaQMCPWXjCkvjUSTfc1sAfASJqrcKS4FHfLvIKpRupe9a5u4tsD8+LLVRnBnk8ZX3rysS4YrSeTjTCDVvuy2IFZyZEpqDLSLkldZXHUxQFXEiMaYYFRVCYU6gcE75kerQS0pQYkBKAtNzVysj7UhDIanEPvClKwv8nhqY/q3u9vv1drK+d4FBKnKJUgj7Kc=
