version: 1.0.0-{build}
image: Visual Studio 2017

environment:
  CMAKE_PREFIX_PATH: C:\Qt\5.9.1\msvc2017_64

build_script:
- cmd: >-
    .\gradlew.bat build

    .\gradlew.bat :skrypton-native:publish

artifacts:
- path: native\build\libs\*.jar
  name: SKryptonNative_Windows64_Release
- path: build\libs\*.jar
  name: SKrypton

environment:
  PUBLISH_API_KEY:
    secure: +mjQC37Gn054BdTkcJSxPlzPt5eJ9DRdQuxJOvPJr8paGGSjC890jMM/zHoomRezwPU3WEO1tPF0qdd6/FiNN3Bz702wpCW7zWcWWD4gRRk=
