/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_JNITest */

#ifndef _Included_com_waicool20_skrypton_jni_JNITest
#define _Included_com_waicool20_skrypton_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_JNITest
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_JNITest_say
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
