/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWebSettings */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWebSettings
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWebSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebSettings
 * Method:    resetAttribute_N
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebSettings_resetAttribute_1N
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebSettings
 * Method:    setAttribute_N
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebSettings_setAttribute_1N
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebSettings
 * Method:    testAttribute_N
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebSettings_testAttribute_1N
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
