/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_QWidget */

#ifndef _Included_com_waicool20_skrypton_jni_objects_QWidget
#define _Included_com_waicool20_skrypton_jni_objects_QWidget
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_QWidget
 * Method:    show_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_QWidget_show_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_QWidget
 * Method:    hide_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_QWidget_hide_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_QWidget
 * Method:    resize_N
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_QWidget_resize_1N
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_waicool20_skrypton_jni_objects_QWidget
 * Method:    dispose_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_QWidget_dispose_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
