/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonMouseEvent */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonMouseEvent
 * Method:    getButton_N
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_getButton_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonMouseEvent
 * Method:    getButtons_N
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_getButtons_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonMouseEvent
 * Method:    getGlobalPos_N
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_getGlobalPos_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonMouseEvent
 * Method:    getScreenPos_N
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_getScreenPos_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonMouseEvent
 * Method:    getLocalPos_N
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_getLocalPos_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonMouseEvent
 * Method:    getSource_N
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_getSource_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
