/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWheelEvent */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWheelEvent
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWheelEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWheelEvent
 * Method:    isInverted_N
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWheelEvent_isInverted_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWheelEvent
 * Method:    getPhase_N
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWheelEvent_getPhase_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWheelEvent
 * Method:    getDelta_N
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWheelEvent_getDelta_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWheelEvent
 * Method:    getLocalPos_N
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWheelEvent_getLocalPos_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWheelEvent
 * Method:    getGlobalPos_N
 * Signature: ()Ljava/awt/Point;
 */
JNIEXPORT jobject JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWheelEvent_getGlobalPos_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWheelEvent
 * Method:    getButtons_N
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWheelEvent_getButtons_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWheelEvent
 * Method:    getSource_N
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWheelEvent_getSource_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
