/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWebView */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWebView
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWebView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebView
 * Method:    dispose_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebView_dispose_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
