/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonKeyEvent_Companion */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonKeyEvent_Companion
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonKeyEvent_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonKeyEvent_Companion
 * Method:    initialize_N
 * Signature: (IJJLjava/lang/String;ZI)J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonKeyEvent_00024Companion_initialize_1N
  (JNIEnv *, jobject, jint, jlong, jlong, jstring, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
