/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWebView_Factory */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWebView_Factory
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWebView_Factory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebView_Factory
 * Method:    initialize_N
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebView_00024Factory_initialize_1N
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
