/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_WebViewHighlighter */

#ifndef _Included_com_waicool20_skrypton_jni_objects_WebViewHighlighter
#define _Included_com_waicool20_skrypton_jni_objects_WebViewHighlighter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
