/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWebProfile_Companion */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_Companion
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile_Companion
 * Method:    defaultProfile_N
 * Signature: ()Lcom/waicool20/skrypton/jni/objects/SKryptonWebProfile;
 */
JNIEXPORT jobject JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_00024Companion_defaultProfile_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile_Companion
 * Method:    initialize_N
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_00024Companion_initialize_1N
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
