/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonResizeEvent */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonResizeEvent
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonResizeEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonResizeEvent
 * Method:    getNewSize_N
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonResizeEvent_getNewSize_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonResizeEvent
 * Method:    getOldSize_N
 * Signature: ()Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonResizeEvent_getOldSize_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
