/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_WebViewHighlighter_Companion */

#ifndef _Included_com_waicool20_skrypton_jni_objects_WebViewHighlighter_Companion
#define _Included_com_waicool20_skrypton_jni_objects_WebViewHighlighter_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_WebViewHighlighter_Companion
 * Method:    initialize_N
 * Signature: (Lcom/waicool20/skrypton/jni/objects/SKryptonWebView;IIIIZIII)J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_WebViewHighlighter_00024Companion_initialize_1N
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jboolean, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
