/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_Companion */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_Companion
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_Companion
 * Method:    initialize_N
 * Signature: (IIIIIIIJJJI)J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonMouseEvent_00024Companion_initialize_1N
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
