/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWebSettings_Companion */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWebSettings_Companion
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWebSettings_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebSettings_Companion
 * Method:    defaultSettings_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebSettings_00024Companion_defaultSettings_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
