/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWidget */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWidget
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWidget
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWidget
 * Method:    show_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWidget_show_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWidget
 * Method:    hide_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWidget_hide_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWidget
 * Method:    resize_N
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWidget_resize_1N
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWidget
 * Method:    dispose_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWidget_dispose_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
