/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWebProfile */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWebProfile
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWebProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    getCachePath_N
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_getCachePath_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setCachePath_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setCachePath_1N
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
