/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonApp */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonApp
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonApp
 * Method:    runOnMainThread_N
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonApp_runOnMainThread_1N
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonApp
 * Method:    initialize_N
 * Signature: ([Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonApp_initialize_1N
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonApp
 * Method:    exec_N
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonApp_exec_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonApp
 * Method:    dispose_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonApp_dispose_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
