/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWebProfile */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWebProfile
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWebProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    getCachePath_N
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_getCachePath_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setCachePath_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setCachePath_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    getHttpAcceptLanguage_N
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_getHttpAcceptLanguage_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setHttpAcceptLanguage_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setHttpAcceptLanguage_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    getHttpCacheMaxSize_N
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_getHttpCacheMaxSize_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setHttpCacheMaxSize_N
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setHttpCacheMaxSize_1N
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    getHttpCacheType_N
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_getHttpCacheType_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setHttpCacheType_N
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setHttpCacheType_1N
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    getHttpUserAgent_N
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_getHttpUserAgent_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setHttpUserAgent_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setHttpUserAgent_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    getPersistentCookiesPolicy_N
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_getPersistentCookiesPolicy_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setPersistentCookiesPolicy_N
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setPersistentCookiesPolicy_1N
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    getPersistentStoragePath_N
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_getPersistentStoragePath_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setPersistentStoragePath_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setPersistentStoragePath_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    isSpellCheckEnabled_N
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_isSpellCheckEnabled_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setSpellCheckEnabled_N
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setSpellCheckEnabled_1N
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    getSpellCheckLanguages_N
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_getSpellCheckLanguages_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    setSpellCheckLanguages_N
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_setSpellCheckLanguages_1N
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    clearAllVisitedLinks_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_clearAllVisitedLinks_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    clearHttpCache_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_clearHttpCache_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebProfile
 * Method:    clearVisitedLinks
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebProfile_clearVisitedLinks
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
