/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonWebView */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonWebView
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonWebView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebView
 * Method:    initialize_N
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebView_initialize_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebView
 * Method:    load_N
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebView_load_1N
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebView
 * Method:    setZoomFactor_N
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebView_setZoomFactor_1N
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonWebView
 * Method:    zoomFactor_N
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonWebView_zoomFactor_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
