/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_waicool20_skrypton_jni_objects_SKryptonKeyEvent */

#ifndef _Included_com_waicool20_skrypton_jni_objects_SKryptonKeyEvent
#define _Included_com_waicool20_skrypton_jni_objects_SKryptonKeyEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonKeyEvent
 * Method:    dispose_N
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonKeyEvent_dispose_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonKeyEvent
 * Method:    getKey_N
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonKeyEvent_getKey_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonKeyEvent
 * Method:    getChar_N
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonKeyEvent_getChar_1N
  (JNIEnv *, jobject);

/*
 * Class:     com_waicool20_skrypton_jni_objects_SKryptonKeyEvent
 * Method:    isAutoRepeat_N
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_waicool20_skrypton_jni_objects_SKryptonKeyEvent_isAutoRepeat_1N
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
